# Generated by Django 6.1 on 2026-08-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_email_verified_emailverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', help_text='Plan de suscripción del usuario (Free o Pro).', max_length=10, verbose_name='plan'),
        ),
    ]
