# Generated by Django 6.1 on 2026-08-13 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('reference', 'Adivinar la referencia'), ('utility', '¿Qué utilidad lanzar?'), ('landing_spot', '¿Dónde cae la utilidad?'), ('key_combo', 'Combinación de teclas'), ('player_position', 'Posición del jugador'), ('map_location', 'Lugares del mapa')], max_length=20, verbose_name='tipo')),
                ('prompt', models.TextField(verbose_name='enunciado')),
                ('helper_text', models.TextField(blank=True, verbose_name='ayuda')),
                ('image_url', models.URLField(blank=True, verbose_name='imagen')),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='maps.lineup')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='maps.map')),
            ],
            options={
                'verbose_name': 'pregunta',
                'verbose_name_plural': 'preguntas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255, verbose_name='texto')),
                ('position_x', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='posición X')),
                ('position_y', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='posición Y')),
                ('is_correct', models.BooleanField(default=False, verbose_name='correcta')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.question')),
            ],
            options={
                'verbose_name': 'opción',
                'verbose_name_plural': 'opciones',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('maps', models.ManyToManyField(blank=True, related_name='quizzes', to='maps.map')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'quiz',
                'verbose_name_plural': 'quizzes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='quiz.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='quiz.quiz')),
            ],
            options={
                'verbose_name': 'pregunta de quiz',
                'verbose_name_plural': 'preguntas de quiz',
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('quiz', 'question'), name='unique_question_per_quiz')],
            },
        ),
    ]
