# Generated by Django 6.1 on 2026-08-20 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_seed_mirage_place_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='correcta')),
                ('answered_at', models.DateTimeField(auto_now_add=True, verbose_name='respondida')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quiz.option')),
                ('quiz_question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='quiz.quizquestion')),
            ],
            options={
                'verbose_name': 'respuesta de quiz',
                'verbose_name_plural': 'respuestas de quiz',
            },
        ),
    ]
