# Generated by Django 6.1 on 2026-08-21 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hard_seconds_per_question', models.PositiveIntegerField(default=20, verbose_name='segundos por pregunta (difícil)')),
            ],
            options={
                'verbose_name': 'configuración de quiz',
                'verbose_name_plural': 'configuración de quiz',
            },
        ),
        migrations.AddField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Fácil'), ('hard', 'Difícil')], default='easy', max_length=10, verbose_name='dificultad'),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='quiz.option'),
        ),
    ]
