# Generated by Django 6.1 on 2026-08-21 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_quizconfig_quiz_difficulty_alter_quizanswer_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('lineup_incorrecto', 'Lineup incorrecto'), ('respuesta_mal', 'La respuesta está mal'), ('otro', 'Otro')], max_length=30, verbose_name='motivo')),
                ('detail', models.TextField(blank=True, verbose_name='detalle')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='quiz.question')),
            ],
            options={
                'verbose_name': 'reporte de pregunta',
                'verbose_name_plural': 'reportes de pregunta',
                'ordering': ['-created_at'],
            },
        ),
    ]
