# Generated by Django 6.1 on 2026-08-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_questionreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='tap_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='toque X'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='tap_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='toque Y'),
        ),
        migrations.AddField(
            model_name='quizconfig',
            name='default_hit_radius',
            field=models.DecimalField(decimal_places=2, default=12, help_text='En unidades 0-100 sobre la imagen. Se usa si el lugar no tiene radio propio.', max_digits=5, verbose_name='radio de zona por defecto'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('reference', 'Adivinar la referencia'), ('utility', '¿Qué utilidad lanzar?'), ('landing_spot', '¿Dónde cae la utilidad?'), ('key_combo', 'Combinación de teclas'), ('player_position', 'Posición del jugador'), ('map_location', 'Lugares del mapa'), ('map_area', 'Zonas del mapa')], max_length=20, verbose_name='tipo'),
        ),
    ]
