# Generated by Django 6.1 on 2026-08-13 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('image_url', models.URLField(blank=True, verbose_name='imagen')),
                ('is_free', models.BooleanField(default=False, verbose_name='gratis')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
            ],
            options={
                'verbose_name': 'mapa',
                'verbose_name_plural': 'mapas',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('position_x', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='posición X')),
                ('position_y', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='posición Y')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='maps.map')),
            ],
            options={
                'verbose_name': 'lugar',
                'verbose_name_plural': 'lugares',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='título')),
                ('util', models.CharField(choices=[('smoke', 'Smoke'), ('flashbang', 'Flashbang'), ('he', 'HE'), ('molotov', 'Molotov'), ('decoy', 'Decoy')], max_length=20, verbose_name='utilidad')),
                ('description', models.TextField(blank=True, verbose_name='descripción')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='maps.place')),
            ],
            options={
                'verbose_name': 'lineup',
                'verbose_name_plural': 'lineups',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.AddConstraint(
            model_name='place',
            constraint=models.UniqueConstraint(fields=('map', 'name'), name='unique_place_per_map'),
        ),
    ]
