# Generated by Django 6.1 on 2026-08-17 00:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(verbose_name='imagen')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado')),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='maps.lineup')),
            ],
            options={
                'verbose_name': 'imagen de lineup',
                'verbose_name_plural': 'imágenes de lineup',
                'ordering': ['order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('lineup', 'image_url'), name='unique_lineup_image_url')],
            },
        ),
    ]
