# Generated by Django 6.1 on 2026-08-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_associate_question_images_to_lineups'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='requires_pro_plan',
            field=models.BooleanField(default=False, help_text='Si es True, solo los usuarios con plan Pro pueden comprarlo.', verbose_name='requiere plan Pro'),
        ),
    ]
