# Generated by Django 6.1 on 2026-08-22 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_set_pro_maps'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='hit_radius',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='radio de zona'),
        ),
    ]
