# Generated by Django 6.1 on 2026-08-22 04:32

from django.db import migrations


def set_hit_radius(apps, schema_editor):
    Place = apps.get_model('maps', 'Place')
    Place.objects.update(hit_radius=5)


def revert_hit_radius(apps, schema_editor):
    Place = apps.get_model('maps', 'Place')
    Place.objects.update(hit_radius=None)


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_place_hit_radius'),
    ]

    operations = [
        migrations.RunPython(set_hit_radius, revert_hit_radius),
    ]
