# Generated by Django 6.1 on 2026-08-13 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.PositiveIntegerField(default=0, verbose_name='experiencia')),
                ('coins', models.PositiveIntegerField(default=0, verbose_name='monedas')),
                ('streak', models.PositiveIntegerField(default=0, verbose_name='racha')),
                ('best_streak', models.PositiveIntegerField(default=0, verbose_name='mejor racha')),
                ('last_streak_at', models.DateTimeField(blank=True, null=True, verbose_name='última racha')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progression', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'progresión',
                'verbose_name_plural': 'progresiones',
            },
        ),
        migrations.CreateModel(
            name='UserMapUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_unlocks', to='maps.map')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_unlocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'desbloqueo de mapa',
                'verbose_name_plural': 'desbloqueos de mapa',
                'constraints': [models.UniqueConstraint(fields=('user', 'map'), name='unique_map_unlock')],
            },
        ),
        migrations.CreateModel(
            name='UserPlaceUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('via', models.CharField(choices=[('free', 'Gratuito (único)'), ('coins', 'Monedas')], default='coins', max_length=10, verbose_name='vía')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_unlocks', to='maps.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_unlocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'desbloqueo de lugar',
                'verbose_name_plural': 'desbloqueos de lugar',
                'constraints': [models.UniqueConstraint(fields=('user', 'place'), name='unique_place_unlock')],
            },
        ),
        migrations.CreateModel(
            name='UserQuestionTypeUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('reference', 'Adivinar la referencia'), ('utility', '¿Qué utilidad lanzar?'), ('landing_spot', '¿Dónde cae la utilidad?'), ('key_combo', 'Combinación de teclas'), ('player_position', 'Posición del jugador'), ('map_location', 'Lugares del mapa')], max_length=20, verbose_name='tipo de pregunta')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_type_unlocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'desbloqueo de tipo de pregunta',
                'verbose_name_plural': 'desbloqueos de tipo de pregunta',
                'constraints': [models.UniqueConstraint(fields=('user', 'question_type'), name='unique_question_type_unlock')],
            },
        ),
    ]
