# Generated by Django 6.1 on 2026-08-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplaceunlock',
            name='via',
            field=models.CharField(choices=[('free', 'Gratuito (único)'), ('starter', 'Inicial'), ('coins', 'Monedas')], default='coins', max_length=10, verbose_name='vía'),
        ),
    ]
