# Generated by Django 6.1 on 2026-08-16 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
        ('progression', '0002_alter_userplaceunlock_via'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLineupUnlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('lineup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_unlocks', to='maps.lineup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_unlocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'desbloqueo de lineup',
                'verbose_name_plural': 'desbloqueos de lineup',
                'constraints': [models.UniqueConstraint(fields=('user', 'lineup'), name='unique_lineup_unlock')],
            },
        ),
    ]
