# Generated by Django 6.1 on 2026-08-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0003_userlineupunlock'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTypeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('reference', 'Adivinar la referencia'), ('utility', '¿Qué utilidad lanzar?'), ('landing_spot', '¿Dónde cae la utilidad?'), ('key_combo', 'Combinación de teclas'), ('player_position', 'Posición del jugador'), ('map_location', 'Lugares del mapa')], max_length=20, unique=True, verbose_name='tipo de pregunta')),
                ('label', models.CharField(max_length=100, verbose_name='etiqueta')),
                ('unlock_level', models.PositiveIntegerField(blank=True, help_text='0 = desde el inicio. 1+ = nivel requerido. Vacío = solo con monedas.', null=True, verbose_name='nivel de desbloqueo')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='orden')),
                ('utility_levels', models.TextField(blank=True, help_text='Solo para "¿Qué utilidad lanzar?": JSON {"smoke": 2, "molotov": 3, "flashbang": 4, "he": 5, "decoy": 6}.', verbose_name='niveles por utilidad')),
            ],
            options={
                'verbose_name': 'configuración de tipo de pregunta',
                'verbose_name_plural': 'configuración de tipos de pregunta',
                'ordering': ['order', 'id'],
            },
        ),
    ]
