# Generated by Django 6.1 on 2026-08-20 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progression', '0005_seed_question_type_configs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoRewardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins', models.PositiveIntegerField(default=200, verbose_name='monedas por video')),
                ('cooldown_hours', models.PositiveIntegerField(default=24, verbose_name='cooldown (horas)')),
                ('enabled', models.BooleanField(default=True, verbose_name='habilitado')),
                ('video_url', models.URLField(blank=True, help_text='URL de un video (placeholder) o, más adelante, el tag HTML/JS de la red de rewarded video (Playwire).', verbose_name='video (URL o tag)')),
            ],
            options={
                'verbose_name': 'configuración de video con recompensa',
                'verbose_name_plural': 'configuración de video con recompensa',
            },
        ),
        migrations.CreateModel(
            name='VideoRewardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True, verbose_name='reclamado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_reward_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reclamo de video',
                'verbose_name_plural': 'reclamos de video',
                'ordering': ['-claimed_at'],
            },
        ),
    ]
