# Generated by Django 6.1 on 2026-08-14 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Crear'), ('update', 'Actualizar'), ('delete', 'Eliminar')], max_length=10, verbose_name='acción')),
                ('app_label', models.CharField(max_length=50, verbose_name='app')),
                ('model_name', models.CharField(max_length=50, verbose_name='modelo')),
                ('object_id', models.CharField(max_length=50, verbose_name='objeto')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='resumen')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='datos')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'ordering': ['-created_at'],
            },
        ),
    ]
